#arithmetic format('%02d'%i)

setup() {  
    load "${BATS_TEST_DIRNAME}/../common/common_setup"
    _common_setup  
}

@test "00. Check tests running on targeted machine" {
    #ATTENTION: IF THIS TESTS FAILS MIGHT BE BECAUSE YOU ARE RUNNING THE CLIENT TEST IN THE WRONG MACHINE,
    #RUN IT IN CLIENT MACHINE INSTEAD
    run hostname
    assert_output 'fw'
}

@test "01. Check packages and other dependencies are installed" {  
    run bats_pipe dpkg-query -l iptables-persistent \| awk '/un|ii/ { print $1 }'
    assert_line 'ii'     
    run bats_pipe dpkg-query -l apache2 \| awk '/un|ii/ { print $1 }'
    assert_line 'un'        
}

#NAT GW Disabled
@test "02. Check eth0 nat gw is disabled" {        
    run bats_pipe route -n \| awk 'NR>2{ print $1" "$2" "$8}'
    refute_line  '0.0.0.0 10.0.2.2 eth0'
}

@test "03. Check 60-routes.yaml exists" {        
    assert_exists '/etc/netplan/60-routes.yaml'        
}

@test "04. Check 60-routes.yaml configured" {        
    run cat '/etc/netplan/60-routes.yaml'        
    assert_line --partial 'via: 192.168.82.100'
}

@test "05. Check default gw is set" {        
    run bats_pipe route -n \| awk 'NR>2{ print $1" "$2" "$8}'
    assert_line  '0.0.0.0 192.168.82.100 eth3'
}



@test "06. check ip forward enabled" {        
    run cat /proc/sys/net/ipv4/ip_forward
    assert_output '1'
}


##RULES
@test "07. Traffic from loopback interface should succeed" {        
    run ping -c 1 -W 0.2 localhost
    [ "$status" -eq 0 ]
}

@test "08. Output traffic  generated by fw should fail" {        
    run ping -c 1 -W 0.2 192.168.82.100
    [ "$status" -ne 0 ]
}