#arithmetic format('%02d'%i)

setup() {  
    load "${BATS_TEST_DIRNAME}/../common/common_setup"
    _common_setup  
    LAN1=lan1
    LAN2=lan2
    FW=firewall
    FW_IP=10.10.81.1
    LAN_NET=10.10.81.*/24

}

#DNS and DNSMASQ configuration
@test "00. [FW]Check firewall network devices names" {
    
    incus exec $FW -- ls -xw0 /sys/class/net | grep lan | grep wan     
}

@test "01. [FW]Check firewall lan ip" {
    
    incus exec $FW -- ip a show lan | grep "$FW_IP"
}

@test "02. [FW]Check packages and other dependencies are installed" {  
    incus exec $FW -- dpkg-query -l dnsmasq | awk '/un|ii/ { print $1 }' | grep 'ii'
    incus exec $FW -- dpkg-query -l nftables | awk '/un|ii/ { print $1 }' | grep 'ii'
    
}

@test "03. [FW]check dnsmasq properly configured" { 
    INCUSBR0_IP4=$(incus network get incusbr0 ipv4.address)
    INCUSBR0_IP4=${INCUSBR0_IP4%/*}

    incus exec $FW -- grep "^server=$INCUSBR0_IP4@wan$" /etc/dnsmasq.d/lan.conf
    incus exec $FW -- grep '^bind-interfaces$' /etc/dnsmasq.d/lan.conf
    incus exec $FW -- grep '^dhcp-option=option:domain-name,asir2.grao' /etc/dnsmasq.d/lan.conf    
    incus exec $FW -- grep '^DNSMASQ_EXCEPT="lo"$' /etc/default/dnsmasq
}

@test "04. [FW]Check systemd-resolved stub disabled figureddnsmasq properly configured" { 
    incus exec $FW -- grep '^DNSStubListener=yes$' /etc/systemd/resolved.conf
}

@test "05. [FW]Check DNSs points to itself" { 
    incus exec $FW -- resolvectl status lan | grep "DNS Servers: $FW_IP"
    incus exec $FW -- resolvectl status lan | grep "DNS Domain: asir2.grao"
    incus exec $FW -- resolvectl status wan | grep "DNS Servers: $ICNUSBR0_IP4"
    incus exec $FW -- resolvectl status wan | grep "DNS Domain: incus"
}

@test "06. [FW]Check DNS records" { 
    incus exec $FW -- host -W1 fw
    incus exec $FW -- host -W1 lan1
    incus exec $FW -- host -W1 lan2
}

@test "07. [FW]Test lan ping and name resolution" { 
    incus exec $FW -- ping -c 1 -W 0.2 lan1
    incus exec $FW -- ping -c 1 -W 0.2 lan2
    incus exec $FW -- ping -c 1 -W 0.2 fw    
}


#LAN CLIENTS SETUP
@test "08. [LAN]Check IP in subnet" { 
    incus exec $LAN1 -- ip a show dev eth0 | grep $LAN_NET
    incus exec $LAN2 -- ip a show dev eth0 | grep $LAN_NET
}

@test "09. [LAN]Check DNS" { 
    incus exec $LAN1 -- resolvectl status eth0 | grep "DNS Servers: $FW_IP"
    incus exec $LAN1 -- resolvectl status eth0 | grep "DNS Domain: asir2.grao"
    incus exec $LAN2 -- resolvectl status eth0 | grep "DNS Servers: $FW_IP"
    incus exec $LAN2 -- resolvectl status eth0 | grep "DNS Domain: asir2.grao"
}


@test "10. [LAN]Check GW " { 
    incus exec $LAN1 -- ip route show default | grep $FW_IP
    incus exec $LAN2 -- ip route show default | grep $FW_IP
}

@test "11. [LAN]Test lan ping and name resolution" { 
    incus exec $LAN1 -- ping -c 1 -W 0.2 lan2
    incus exec $LAN1 -- ping -c 1 -W 0.2 fw
    incus exec $LAN2 -- ping -c 1 -W 0.2 lan1
    incus exec $LAN2 -- ping -c 1 -W 0.2 fw    
}


#ROUTING FW
@test "12. [FW]check ip forward enabled" {        
    incus exec $FW -- grep '1' /proc/sys/net/ipv4/ip_forward
}





#NAT GW Disabled
@test "13. Check eth0 nat gw is disabled" {        
    skip
    run bats_pipe route -n \| awk 'NR>2{ print $1" "$2" "$8}'
    refute_line  '0.0.0.0 10.0.2.2 eth0'
}

@test "14. Check 60-routes.yaml exists" {        
    skip
    assert_exists '/etc/netplan/60-routes.yaml'        
}

@test "15. Check 60-routes.yaml configured" {        
    skip
    run cat '/etc/netplan/60-routes.yaml'        
    assert_line --partial 'via: 192.168.82.100'
}

@test "16. Check default gw is set" {        
    skip
    run bats_pipe route -n \| awk 'NR>2{ print $1" "$2" "$8}'
    assert_line  '0.0.0.0 192.168.82.100 eth3'
}


##RULES
@test "17. Traffic from loopback interface should succeed" {        
    skip
    run ping -c 1 -W 0.2 localhost
    [ "$status" -eq 0 ]
}

@test "18. Output traffic  generated by fw should fail" {        
    skip
    run ping -c 1 -W 0.2 192.168.82.100
    [ "$status" -ne 0 ]
}